# Define the default driver
#webdriver.driver=phantomjs
 
# Appears at the top of the reports
serenity.project.name = Demo Project using Serenity and JUnit

webdriver.autodownload = false
webdriver.driver = chrome
headless.mode = false

webdriver.firefox.driver = src/test/resources/windows/geckodriver.exe
webdriver.chrome.driver = src/test/resources/windows/chromedriver.exe
# Pentru Firefox se descarca ultima versiune geckodriver.
# Pentru Chrome se deverifica daca ultima versiune (sau cea stabila) a chromedriver este buna. Altfel, se foloseste o versiune anterioara.


# Root package for any JUnit acceptance tests
serenity.test.root=webFTP.features

# Customise your riequirements hierarchy
#serenity.requirement.types=feature, story

# Run the tests without calling webdriver - useful to check your JUnit wireing
#serenity.dry.run=true

# Customise browser size
#serenity.browser.height = 1200
#serenity.browser.width = 1200


